# Generated by Django 3.0.2 on 2020-02-19 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_user_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pictures'),
            preserve_default=False,
        ),
    ]
