# Generated by Django 3.0.2 on 2020-01-27 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_user_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
